######################################################################
# Automatically generated by qmake (2.01a) mié ene 20 00:06:12 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dadero.h
FORMS += dadero.ui
SOURCES += dadero.cpp main.cpp
RESOURCES += resources.qrc
